### ISSUE TITLE
implement std::ffi (CStr, CString, OsStr, OsString)

### ISSUE THREAD

**Issue by japaric** [japaric/steed#3]
This should mostly involve copy pasting the code from rust-lang/rust

**Comment by japaric** [comment]
Done in #42

**Comment by briansmith** [comment]
IMO, it would have been better to go longer without implementing `CStr` and `CString`, and actually it would make sense to revert them. Nothing internally in steed should use those and they don't make sense for type of application that would want to use steed because they are inherently unsafe constructs.

**Comment by japaric** [comment]
>  Nothing internally in steed should use those

Some syscalls like `open` have arguments that are C (null terminated) strings.
